/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 95b99be6226d9775287d51acdf775471)
interface __BaseEnv_Env {
  XGET_ALLOWED_CLIENT_IPS: '1.14.95.189';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./adapters/workers/production');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'XGET_ALLOWED_CLIENT_IPS'>> {}
}
